### ISSUE TITLE
ReferenceError: org is not defined

### ISSUE THREAD

**Issue by Parakleta** [wilmoore/cometd-jquery#2]
Trying to use this package with webpack and I get a ReferenceError because [org/cometd.js#L18](https://github.com/wilmoore/cometd-jquery/blob/73f541a914d9263197c39218cfe6ac0b0ee0ebba/org/cometd.js#L18) sets `this.org` and then assumes that `org` will be available as a local/global variable.

Changing this line to `var org = this.org = this.org || {};` will resolve the problem.

As a workaround I have added the following to my `webpack.config.js` file:

``` js
module: {
  loaders: [
    { test: /org\/cometd\.js$/,
      loader: 'imports?org=>{}'
  ]
}
```

**Comment by dwiyatci** [comment]
I guess that's just the way to do it when we're bundling with webpack.

I import `window` to be the global object and some imports for AMD and jQuery related-stuff:

```
module: {
  loaders: [
    {
      test: /org\/cometd/,
      loader: 'imports?this=>window',
    },
    {
      test: /jquery\.cometd\.js$/,
      loader: 'imports?this=>window,define=>false,jQuery=jquery',
    },
  ],
},
```

**Comment by wilmoore** [comment]
Wow man...all this loader stuff is still a huge mess. Glad you figured it out. It would be really cool to add something to the readme for others that are having the same issue. I'll close this but would be happy to accept a tiny PR for a readme update.
